"""Safe interfaces for future real cement/clinker ML architecture.

This package intentionally defines architecture, schemas, and validation logic for
future industrial cement/clinker modelling. No real model training or synthetic
label generation is performed here.
"""

from .cement_ml_architecture import (
    ALLOWED_GROUND_TRUTH_CATEGORIES,
    MEASURED_GROUND_TRUTH_CATEGORIES,
    REFERENCE_GROUND_TRUTH_CATEGORIES,
    TargetDefinition,
    TargetTaxonomy,
    FeatureAvailabilityLevel,
    FeaturePolicyEntry,
    FeaturePolicy,
    ProvenanceMetadata,
    RawMaterialRecord,
    RawMixRecord,
    KilnFeedRecord,
    ProcessRecord,
    HotMealRecord,
    ClinkerMeasurement,
    CementMeasurement,
    MLTrainingRecord,
    MLPrediction,
    PredictionMetadata,
    OODResult,
    UncertaintyResult,
    ValidationResult,
    TemporalAlignmentConfig,
    align_process_to_target,
    ChronologicalSplitConfig,
    create_chronological_split,
    ModelConfig,
    PhysicsValidationConfig,
    validate_phase_prediction,
    StoichiometricReconstructionResult,
    reconstruct_oxide_from_phases,
    PredictionExplanation,
    InverseOptimizationConfig,
    LLMToolRequest,
    LLMToolResponse,
)

__all__ = [
    "ALLOWED_GROUND_TRUTH_CATEGORIES",
    "MEASURED_GROUND_TRUTH_CATEGORIES",
    "REFERENCE_GROUND_TRUTH_CATEGORIES",
    "TargetDefinition",
    "TargetTaxonomy",
    "FeatureAvailabilityLevel",
    "FeaturePolicyEntry",
    "FeaturePolicy",
    "ProvenanceMetadata",
    "RawMaterialRecord",
    "RawMixRecord",
    "KilnFeedRecord",
    "ProcessRecord",
    "HotMealRecord",
    "ClinkerMeasurement",
    "CementMeasurement",
    "MLTrainingRecord",
    "MLPrediction",
    "PredictionMetadata",
    "OODResult",
    "UncertaintyResult",
    "ValidationResult",
    "TemporalAlignmentConfig",
    "align_process_to_target",
    "ChronologicalSplitConfig",
    "create_chronological_split",
    "ModelConfig",
    "PhysicsValidationConfig",
    "validate_phase_prediction",
    "StoichiometricReconstructionResult",
    "reconstruct_oxide_from_phases",
    "PredictionExplanation",
    "InverseOptimizationConfig",
    "LLMToolRequest",
    "LLMToolResponse",
]
